Write a function so that the columns of the output matrix are powers of the input vector.

The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.

In [19]:
import numpy as np

def aVandermonde(l, N, increasing = True):
    if increasing:
        print(np.array([ j** i for j in l for i in range(N)]).reshape(len(l), N))
    else:
        print(np.array([ j** (N-1-i) for j in l for i in range(N)]).reshape(len(l), N))
        
mylst = [1,2,3]
N = 4
a = 'increasing'
print(a.center(50,'-'))

aVandermonde(np.array(mylst),N)

b= 'decreasing'
print(b.center(50,'-'))
aVandermonde(np.array(mylst),N, increasing= False)

--------------------increasing--------------------
[[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]]
--------------------decreasing--------------------
[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]]


Problem Statement 2: Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows: The moving average sequence has n-k+1 elements as shown below. The moving averages with k=4 of a ten-value sequence (n=10) is shown below

i 1 2 3 4 5 6 7 8 9 10

===== == == == == == == == == == ==

Input 10 20 30 40 50 60 70 80 90 100

y1 25 = (10+20+30+40)/4

y2 35 = (20+30+40+50)/4

y3 45 = (30+40+50+60)/4

y4 55 = (40+50+60+70)/4

y5 65 = (50+60+70+80)/4

y6 75 = (60+70+80+90)/4

y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [44]:
import numpy as np
def moving_average(n,k):
    s=0
    for i in range(a):
        for j in range(i,i+k):
            s+=n[j]
            #print(seq[j],end="")
        print(f'y{i+1} = ',end='')
        print(s/k)
        
seq = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] 
n=np.array(seq)
k=3
a=len(seq)-k+1
print(f'Thus, the moving average sequence has a values.')
moving_average(n,k)

Thus, the moving average sequence has a values.
y1 = 5.0
y2 = 9.666666666666666
y3 = 15.333333333333334
y4 = 22.0
y5 = 31.666666666666668
y6 = 60.333333333333336
y7 = 109.66666666666667
y8 = 182.33333333333334
y9 = 266.3333333333333
y10 = 359.6666666666667
y11 = 476.0
